<div class="main-content">
    <div id="hints-wrapper">
    </div>
    <div class="section-wrapper">
        <div class="header">
            <div class="title"><h1>Editar contacto</h1></div>
            <div class="actions"></div>
        </div>
        <div class="content"></div>
    </div>
    <div id="generalContainer">
        <div id="addClient"></div>
        <div class="required-anotation">Los campos marcados con <span class="req no-padding">*</span> son obligatorios</div>
    </div>
    
    <div id="addContact"></div>
    <!--<a id="addOtherContact">Asociar Persona</a>-->
    <div id="buttonsHolder"></div>
</div>