<div class="main-content">
    <div id="hints-wrapper">
        <div class="hint" style="background-color: #f9d863; border-color: #eeb60a; ">
        	<div class="header">
                <div class="title"><h1 style ="color:#58595f ;">Con Alegra puedes adjuntar archivos en</h1></div>
            
        </div>
        <div class="content">
            <div class="text" style="color: #58595f; float: left;">facturas, transacciones, productos, contactos y otros documentos.</div>
        </div>
        <div class="footer" style="float : right; color: #58595f ">
            <a href="http://ayuda.alegra.com/hc/es/articles/205762029" target="_blank" style="float : right; color: #58595f">Ver más</a>
        </div>
        <div class="closeButton" data-hint-id="137" style="color: #58595f ">x</div>
    </div>
	</div>
	<div class="section-wrapper">
	    <div class="header">
	        <div class="title"><h1>Contactos</h1></div>
	        <div class="actions">
	        	<a href="/index/add" class="button green">
	        		<span class="plus"></span>Nuevo contacto</a>
	        		<a style="margin-left:20px" href="#">Importar desde excel</a>
	        		<style>.section-wrapper .header { position: relative }</style>
                    <a id=downloadClients style="position: absolute;right: 14px;bottom: 13px;color: rgb(167, 164, 164);" href="#">Exportar</a>
	        </div>
	    </div>
	    <div class="content"></div>
	</div>
	<div id="tooltip-many-selections" class="tooltip-wrapper" style="margin-left: -347px; margin-top: 105px; z-index: 11; display: none;">
	        <img class="tooltip" src="https://cdn1.alegra.com/images/icons/help.png">
	        <div class="tooltip-text-container" style="margin-top: -35px; margin-left: -100px">
	            <div class="tooltip-text-wrapper">
	                <div class="text" style="margin: 1px;">Para conocer más sobre la selección múltiple, haz <a target="_blank" href="http://ayuda.alegra.com/hc/es/articles/115000604206-Selecci%C3%B3n-M%C3%BAltiple-para-Operaciones-Masivas"> clic aquí</a>.</div>
	            </div>
	        </div>
	</div>

	<div id="gridClients"></div>
	
</div>